### ISSUE TITLE
--napi-modules flag is not inherited by spawned processes

### ISSUE THREAD

**Issue by jasongin** [nodejs/abi-stable-node#164]
I built node with the `--napi-modules` flag switched to *off by default*, as we plan to have it in the PR. (Currently it is on by default to make our N-API development activity more convenient.)

While N-API can be enabled for a node process by passing `--napi-modules` on the command-line, that enablement doesn't get inherited by spawned processes. In particular this is a problem for test runners, which typically spawn separate processes in which to run tests.

For example, the node-canvas package uses the mocha test runner:

```
node --napi-modules .\node_modules\mocha\bin\mocha test\*.test.js

module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The module '\\?\D:\canvas\canvas-napi\build\Release\canvas.node'
was compiled against the Node.js API. This feature is
experimental and must be enabled on the command-line.
```

Mocha happens to offer a way to run tests in-proc, using its underscore-prefixed executable. So that is a workaround in this case:
```
node --napi-modules .\node_modules\mocha\bin\_mocha test\*.test.js

   canvas: 1.6.0
   cairo: 1.10.2

  Canvas
(node:48060) Warning: N-API is an experimental feature and could change at any time.
    √ should require new
    √ .version
    √ .cairoVersion
    √ .parseFont()
    √ color serialization
```

I'm concerned this could cause trouble with other tests runners or other spawn scenarios that might like to use N-API modules while the feature is still in experimental stage.

**Comment by gabrielschulhof** [comment]
There is no easy way around this, I'm afraid. You simply have to visit every spot where you spawn node and append that switch. In the `test/addons-abi/testcfg.py` we can specify this with the `additional_flags` parameter, because the test runner has a facility for conveying arguments to node, but mechanisms will have to be provided by all projects wishing to do this.

I mean, we could switch to a required environment variable, because processes do inherit the environment by default.

In a way though, this is as it should be. After all, `--expose_gc` isn't inherited either, AFAIK.

**Comment by jasongin** [comment]
Closing because this can be worked around now using [`NODE_OPTIONS`](https://nodejs.org/dist/latest-v8.x/docs/api/cli.html#cli_node_options_options).
