### ISSUE TITLE
Merge napi_handle_scope and napi_escapable_handle_scope into napi_scope

### ISSUE THREAD

**Issue by jasongin** [nodejs/abi-stable-node#177]
As @digitalinfinity, @boingoing, and I discussed offline, there is an opportunity to simplify the API somewhat and make it more abstracted from V8 specifics. We could have a single `napi_open_scope` API that takes a boolean (or flags?) parameter indicating whether it should be escapable. The escapable attribute of a scope would be tracked internally, and if you try to call `napi_escape` on a scope that was not created as escapable, it would return an error.

**Comment by kkoopa** [comment]
What would the actual benefits of that be? Replacing two simple types with one complex is not necessarily a simplification. Now you need to keep track of what arguments were passed to the constructor instead of just looking at the type. It the proposed parameter is a formal parameter it will consume space for no good reason, if it is a template parameter you effectively have two distinct types, so the point is moot.

The only actual simplification would be to ignore `HandleScope` and use `EscapableHandleScope` everywhere. There is a distinction between escapable and ordinary handle scopes purely from a performance optimizatiton point of view. The ordinary HandleScope does not need to reserve a slot for the return value.

**Comment by jasongin** [comment]
As stated above, the main benefit is a simpler public API surface (fewer types and fewer APIs). I'm not saying this is definitely something that must be done, but something to investigate and consider further.

**Comment by mhdawson** [comment]
The other though I had while writing up the documentation is if we should remove the "Handle" from the scope names.  This is something else that cam from V8.    In terms of whether we keep 1 method with a flag or 2 methods, I don't have a strong feeling.  Either way as @kkoopa mentions there is a difference so we want the caller to indicate which of the 2 they need.  If I had to chose right now I'd say just leave as is.

**Comment by jasongin** [comment]
Yes, removing "handle" from the scope names is something we had also discussed.

@mhdawson I think the bigger question is whether the escapable scope is a separate type: is there just one `napi_scope` type, or both `napi_scope` and `napi_escapable_scope`?

**Comment by ianwjhalliday** [comment]
Handle scopes are a critical to understand concept for achieving good performance with v8.  This is a concept I felt should be well understood by the API users, hence exposing it rather transparently.

With a GC like ChakraCore's this concept is moot, and in SpiderMonkey my hand waving conclusion was it was adaptable.  I don't recall what I thought about this concept with respect to an engine like DukTape.

**Comment by ianwjhalliday** [comment]
Which is to say, `napi_scope` to me seems to no longer express its purpose clearly.  Maybe `napi_gc_scope`?

My opinion is to not change it.

**Comment by digitalinfinity** [comment]
Decided to leave as is
