### ISSUE TITLE
Promise?

### ISSUE THREAD

**Issue by martijnthe** [nodejs/abi-stable-node#242]
Hi, I just glanced over the [current API draft] and noticed there is no ES6 Promise API, for example `napi_create_promise()` etc. Is this just not done yet? Or is there another reason why it is not there?

I was hoping to find a NAPI interface for it so we can make sure we are not creating an impedance mismatch with our design of the [JerryScript C Promise API] (feedback appreciated ;)).

[current API draft]: https://github.com/nodejs/abi-stable-node/blob/api-prototype-8.x/src/node_api.h
[JerryScript C Promise API]: https://github.com/jerryscript-project/jerryscript/pull/1796

**Comment by gabrielschulhof** [comment]
@martijnthe there are some conceptual differences between N-API design and JerryScript API design:
- in N-API we pass the context as an explicit parameter to each API rather than having it implicit inside the implementation
- All N-API APIs return a status to indicate whether the call was successful or not.
- JS exceptions are implemented as a check-last-error concept, rather than an error flag on a JS value
- JerryScript does not use scopes, but rather expects each value to be released explicitly

I have started to [implement](https://github.com/gabrielschulhof/zephyr.js/blob/zjs-ocf-btw/src/zjs_node_api.c) N-API using JerryScript in Zephyr.js (still a *very* early draft), and so far I have not found any problems bridging the two APIs.

You're right though, we should tackle ES promises in N-API.
