### ISSUE TITLE
SpiderNode support?

### ISSUE THREAD

**Issue by nschonni** [nodejs/abi-stable-node#253]
Came across https://github.com/mozilla/spidernode/issues/388 and didn't see much besides a reference in the meeting minutes as a bullet point in this repo.

**Comment by digitalinfinity** [comment]
I don't believe SpiderNode supports N-API modules yet- cc @mykmelez in case I'm mistaken.

**Comment by mykmelez** [comment]
> I don't believe SpiderNode supports N-API modules yet- cc @mykmelez in case I'm mistaken.

You're not mistaken! Unfortunately, SpiderNode doesn't yet support N-API modules.

**Comment by jasongin** [comment]
To further clarify, it should be up to the SpiderNode team, not the N-API working group, to add SpiderNode support for N-API. We would be thrilled to work with them on that though!

(The reason why Node-ChakraCore has N-API support already is because the ChakraCore team was directly involved in the N-API effort.)

**Comment by nschonni** [comment]
Should I close this issue, or do you want to keep it open for tracking?

**Comment by mhdawson** [comment]
I think we can close as it should still be discover-able.  As mentioned by @jasongin we would be happy to work with the SpiderNode team but don't have plans to do that on own own right now.
