### ISSUE TITLE
Get node-test-node-addon-api green on windows

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#289]
Works ok except on 10 nightly
	
Info to reproduce steps in the build job
```
https://nodejs.org/download/nightly/v10.0.0-nightly201801043f2382bd9a/
node -v
  npm -v
  export npm_loglevel=error
  npm set progress=false
  ls

  git clone https://github.com/$GIT_REPO.git node-addon-api
  cd node-addon-api
  if [ $GIT_BRANCH != "master" ]; then
  git fetch origin $GIT_BRANCH:testBranch
  git checkout testBranch
  fi
  npm install

  # This line needs to be updated to use the configuration string to test right version
  # citgm -v verbose --tmpDir $WORKSPACE/tmp https://github.com/$NODEREPORT_REPO/archive/$NODEREPORT_BRANCH.tar.gz

  npm test

```

**Comment by digitalinfinity** [comment]
This is because node on windows uses version strings with the style "v10.0.0-pre" instead of "v10.0.0-nightly20171202c589561aaf" (which is what other platforms use). This first showed up on nightly/10.0.0-nightly20171203fff4272fa7 (it was fine as of nightly/10.0.0-nightly20171202c589561aaf). Looking at the commits between those two builds, nodejs/node@9fb390a1c6 seems to be the likely change (although it could be a build issue too). @refack can you help please? With the current behavior, it doesn't seem like node-gyp would work against windows nightly builds.

cc @nodejs/build

**Comment by rvagg** [comment]
```
-call :run-python configure %configure_flags% --dest-cpu=%target_arch% --tag=%TAG% %link_module%
+call :run-python configure %configure_flags%
```

(in @digitalinfinity's commit link)

`./configure --tag foo` -> `'defines': [ 'NODE_TAG="<(node_tag)"' ]` in node.gypi -> src/node_version.h:

```
#ifndef NODE_TAG
# if NODE_VERSION_IS_RELEASE
#  define NODE_TAG ""
# else
#  define NODE_TAG "-pre"
# endif
#else
```

**Comment by rvagg** [comment]
https://github.com/nodejs/node/pull/18031

**Comment by aruneshchandra** [comment]
@mhdawson will start CI on this

**Comment by mhdawson** [comment]
CI is now green, looks good.
