### ISSUE TITLE
Does `resource_name` require a reference?

### ISSUE THREAD

**Issue by jorangreef** [nodejs/abi-stable-node#341]
Thanks to the team for creating N-API, I'm really enjoying working with it compared to NAN.

When creating a `resource_name` string to be passed to `napi_create_async_work`, does one also need to call `napi_create_reference` on the `resource_name` string so that it persists during the lifetime of the `async_work`?

Or is the following adequate?

```c
napi_value resource_name;
napi_create_string_utf8(env, "@ronomon", NAPI_AUTO_LENGTH, &resource_name);
napi_create_async_work(env, NULL, resource_name, [...]);
// Note: We do not ever need to call napi_create_reference on resource_name.
```

Also, a followup question, is there any way one could just supply NULL as `resource_name` to use a generic default (e.g. add a default `resource_name` like `NAPI_ASYNC_WORK`) to cut down on this boilerplate? Perhaps the docs could give more motivation as to why `resource_name` is worth the effort?

**Comment by gabrielschulhof** [comment]
N-API does not support obtaining a reference to a `napi_value` that is not an object. That's because obtaining a reference to a primitive value is not supported on all engines, and is almost never needed. Thus, passing the `napi_value` created with `napi_create_string_utf8` is sufficient.

Having a name for an async work item allows one to distinguish between different async work items in the debugging tools.

**Comment by ralphtheninja** [comment]
> Also, a followup question, is there any way one could just supply NULL as `resource_name` to use a generic default (e.g. add a default `resource_name` like `NAPI_ASYNC_WORK`) to cut down on this boilerplate?

That would be handy indeed.

**Comment by jorangreef** [comment]
Thanks @gabrielschulhof
