### ISSUE TITLE
Old issues and PRs on the node-addon-examples

### ISSUE THREAD

**Issue by NickNaso** [nodejs/abi-stable-node#348]
Hi everyone,
we are starting to work on examples to the https://github.com/nodejs/node-addon-examples repo. I noted that there are very old issues and PRs on this repo. How should we proceed?

**Comment by mhdawson** [comment]
I think its worth going through them and either accepting or closing them.

I close a couple.

I think in many cases we could say that the focus of the repo is now N-API examples and therefore the issue is stale, along with the request for the originator to let us know if they dis-agree with closing.

**Comment by NickNaso** [comment]
Ok thanks I will work as you suggested.
