### ISSUE TITLE
Design for NAPI error handling 

### ISSUE THREAD

**Issue by aruneshchandra** [nodejs/abi-stable-node#37]
Publish and review design document for NAPI error handling

**Comment by aruneshchandra** [comment]
The design needs to also address #27 Correct abstraction for try/catch

**Comment by boingoing** [comment]
Node.js API doesn't yet handle any of the errors which may be encountered within the API itself. Some of the errors can cause AV while others can silently fail and the consumer of the API would not know if the operation was successful. We need to consider what degree of handling we want to implement. Should the API be paranoid about incoming pointers or skip null checks in favor of informing the caller via AV at runtime? How is an error reported to the user of the API and how detailed is that error? This document attempts to outline the issues we need to consider and provides a rough first-pass guide to the design.

To answer the question of how to convey the presence of an error we have a couple of design options:
- Flat error codes like enum or constant integer values as return from API calls
- Optional out-parameter added to each API for error information passed via a structure similar to nserror in iOS development in Objective-C
- Throw exceptions from inside API calls in error cases

Throwing exceptions is a non-starter since we want this API to be flat C. Adding C++ exceptions there would make the API unstable. It's possible for a C++ wrapper of Node.js API to consume one of the other types of error information and throw exceptions. This would not be internal to NAPI, though, which puts it outside the scope of this document.

Optional-out parameter for extra error information seems plausible. More information can flow upstream to provide better error information - perhaps via a future C++ wrapper around NAPI which supports throwing exceptions up to native module code. Concern that the structure of the container for extra information and the added parameter for every API call will make breakages of NAPI more common. 

Similar to the structure of a container for extra error information, concern is also raised over a fixed set of error codes - how do we extend this without breaking the API? Are we safe if the set of error codes is strictly additive? Can we retire error codes?

For the purpose of this document, we will present a design where errors are communicated via simple, integer return values with more error details available via an API call. This design is based on the Node 6 branch of abi-stable-node.

The work in progress for this design is in this fork of abi-stable-node - https://github.com/boingoing/abi-stable-node/tree/error-handling-prototype-6.2.0.

```c++
enum napi_errorvalue {
  napi_ok,
  napi_invalid_arg,
...
  napi_object_expected,
  napi_generic_failure
};

struct napi_extended_error_info {
  const char* error_message;
  void* engine_reserved;
  uint32_t engine_error_code;
  napi_errorvalue error_code;
};

const napi_extended_error_info* napi_get_last_error_info();

// napi_has_element currently (no handling of errors):
bool napi_has_element(napi_env e, napi_value o, uint32_t i) {
  v8::Local<v8::Object> obj = v8impl::V8LocalValueFromJsValue(o)->ToObject();

  return obj->Has(i);
}

// napi_has_element with error handling prototype:
napi_errorvalue napi_has_element(napi_env e, napi_value o, uint32_t i, bool* has) {
  if (!has) {
    return napi_invalid_arg;
  }

  v8::Isolate *isolate = v8impl::V8IsolateFromJsEnv(e);
  v8::Local<v8::Context> context = isolate->GetCurrentContext();
  auto obj_maybe = v8impl::V8LocalValueFromJsValue(o)->ToObject(context);

  if (obj_maybe.IsEmpty()) {
    return napi_object_expected;
  }

  v8::Maybe<bool> has_maybe = obj_maybe.ToLocalChecked()->Has(context, i);

  if (has_maybe.IsNothing()) {
    return napi_generic_failure;
  }

  *has = has_maybe.FromMaybe(false);
  return napi_ok;
}
```

Questions:

- Do we make a distinction between engine error codes and spec-violations or failures?
We can expose an engine-specific pointer in the extended error info object for engine errors. A wrapper could conusme that data and present it somehow. Should we do that?

- Related, how close to the Ecmascript spec do we want to make the Node.js API surface?
If we try to set a property on an object which has the property already as non-writable, should we set the property anyway? Or return an error code?

- Do we validate pointers to the API or allow for AV? 
It's safer to check for nullptr and return an error here but do we want to skip that check and assume the caller will take responsibility for an AV?

- Lifetime of extended error info object? 
Do we just keep a static one object and always return a reference to that one? 
When is it initialized - is a default ctor good? Should we instead copy the fields into another struct allocated by the caller?

- When is extended error info updated? 
Is it ok if we only update this struct when there is an error?
Can we return the result of some method which saves the last error value in some static error info object?
```c++
napi_errorvalue napi_set_last_error_code(napi_errorvalue error_code) {
  return static_last_error.error_code = error_code;
}

...
  if (has_maybe.IsNothing()) {
    return napi_set_last_error_code(napi_generic_failure);
  }
...
```
- Can we delay updating the extended error information until we want to get it?
Seems like we could as long no one keeps a reference to our static napi_extended_error_info and accesses it without going through our API.
```c++
const napi_extended_error_info* napi_get_last_error_info() {
  // Wait until someone requests the last error information to fetch the error message string
  static_last_error.error_message = error_messages[static_last_error.error_code];

  return &static_last_error;
}
```

**Comment by aruneshchandra** [comment]
This was reviewed by the team on Jan 13th meeting - here are some of the notes:

- Do we make a distinction between engine error codes and spec-violations or failures?
_Yes but we need more discussion about how to make the distiction between the different types of failures_

- Related, how close to the Ecmascript spec do we want to make the Node.js API surface?
_Still being discussed_ 

- Do we validate pointers to the API or allow for AV?
_For now we should validate the pointers - but if there are perf impact then we can revisit this decision._

- Lifetime of extended error info object?
_napi_free_extended_error_info or something along those lines _ 

- When is extended error info updated?
_When we encounter the error - we set some parts of the extended error info in the object which then can be used to fill out more details on demand._  

- Can we delay updating the extended error information until we want to get it?
_Yes_

- How to address handling of pending exception using NAPI?
_Garbiel's design of Try/Catch seems reasonable at this time. We want to store the exception when it happens and throw it back on script entry if it is still pending._

- What is the optimal API shape for retrieving extended error info?
_Pass the object and needed to be filled out or get a pointer back. Current implementation is going return a pointer to a static object._

- How to handle lifetime of the extended error object which might contain engine specific data?
_napi_free_extended_error_info or something along those lines_
