### ISSUE TITLE
renaming n-api to something more appropriate and descriptive

### ISSUE THREAD

**Issue by jasnell** [nodejs/abi-stable-node#420]
`N-API` is a poorly selected name for the ABI-stable API for native addons. While the intent is for the name to be pronounced "En-Ay-Pee-Eye", it is most often colloquially reduced to "nappy", which -- if you're unfamiliar -- is term often used in English as a derogatory way describing the hair of black people. Aside from that, it's just not actually descriptive of what the API is for.

I'd like to propose "Stable ABI" (or S-ABI for short) as an alternative.  (@addaleax has suggested C-API as a viable alternative also... based on the fact that, well, "that's exactly what it is" 🤣... that would work also)

I can open a PR to update all of the references in project but wanted to determine the support. I'd rather not spend a ton of time bike-shedding alternative names.

There's been some adoption of the API in other projects so the old name certainly won't disappear entirely overnight, but renaming it here would be a great step in the right direction.

/cc @addaleax @nodejs/tsc

**Comment by jschlight** [comment]
As we are moving forward with this initiative, I thought I'd collect some ideas for further discussion and planning by the N-API team and others. Here are some aspects we need to consider:

- Have we decided on `NODE-API` as the new name? - YES
- What is our pattern for naming new symbols? - use node_api_ instead of napi_ to prefix new symbols
- What is our approach for existing symbols? - leave as is
- What locations of the Node.js core documentation need to be updated? - update wherever possible
- What locations of ancillary repositories like `node-addon-api` need to be updated? - the others repos this team manages (node-addon-api, node-addon-examples, new headers repo)
- What related projects such as `node-gyp`, `node-pre-gyp`, etc. need to be updated? - Jim will add comment on this issue were docs may need to be updated.
- How will these updates be accomplished? - We can PR them?
- What sort of outreach to the wider Node community do we need to make and what is our message?
  - plan is to frame as "clarification of what was already the name", hopefully does not need much messaging/clarification.

**Comment by gabrielschulhof** [comment]
At today's TSC meeting we concluded that, for the time being, we will replace documentation references to N-API with Node-API, stopping short of providing C preprocessor aliases for our symbols and public macros. We may make deeper changes if, after these changes, we feel that further changes are warranted.

**Comment by jschlight** [comment]
These are projects that facilitate the building of Node-API modules. Some of them include documentation that refers to N-API. 

### Docs
- [x] N-API resource - http://nodejs.github.io/node-addon-examples/
- [x] node-addon-api - https://github.com/nodejs/node-addon-api

### Related Node-API Build Tools

- [x] [`node-gyp`](https://github.com/nodejs/node-gyp) – Documentation does not refer to `N-API`.
- [ ] [`CMake.js`](https://github.com/cmake-js/cmake-js) – [PR submitted](https://github.com/cmake-js/cmake-js/pull/239)
- [x] [`node-pre-gyp`](https://github.com/mapbox/node-pre-gyp)  – [PR landed](https://github.com/mapbox/node-pre-gyp/pull/580)
- [x] [`prebuild`](https://github.com/prebuild/prebuild) – [PR landed](https://github.com/prebuild/prebuild/pull/276)
- [x] [`prebuild-install`](https://github.com/prebuild/prebuild-install) – Documentation does not refer to `N-API`.
- [x] [`node-gyp-build`](https://github.com/prebuild/node-gyp-build) – Documentation does not refer to `N-API`.
- [x] [`prebuildify`](https://github.com/prebuild/prebuildify) – [PR landed](https://github.com/prebuild/prebuildify/pull/50)
- [x] [`prebuildify-ci`](https://github.com/mafintosh/prebuildify-ci) – Documentation does not refer to `N-API`.

Since I've contributed to most of the projects that need documentation updates, I will go ahead and create the necessary PRs.

**Comment by NickNaso** [comment]
Should we change the blog posts we wrote for the Node.js Collections?

**Comment by mhdawson** [comment]
@NickNaso I think we are probably ok leaving those as is.

**Comment by jschlight** [comment]
One last thing I see that should be fixed is the GitHub About box for https://github.com/nodejs/node-addon-api

**Comment by mhdawson** [comment]
@jschlight - DONE

**Comment by mhdawson** [comment]
Looks like we are done based on update from @jschlight in last Node-API team meeting, closing.

**Comment by StephenLynx** [comment]
This is stupid and unnecessary friction.

**Comment by FrankFang** [comment]
There is an old Chinese saying "吃饱了撑得没事干".
It means "what you are doing is wasted effort"
