### ISSUE TITLE
Bugs in napi_get_string_from_value

### ISSUE THREAD

**Issue by jasongin** [nodejs/abi-stable-node#63]
I found multiple problems with the current implementations of `napi_get_string_from_value`: 
 * The function is currently defined as returning the number of bytes _remaining_ in 
the buffer. This is different from both [V8](https://v8docs.nodesource.com/node-0.8/d2/db3/classv8_1_1_string.html#a237a2b794f31d8c60d9561ad3b30248e) and [JSRT](https://github.com/Microsoft/ChakraCore/wiki/JsCopyStringUtf8) string APIs, which always return the number of bytes 
_written_. I think this behavior will definitely confuse some people and cause bugs, so it should be fixed. 
 * In the part of the V8 implementation that copies a stringified number value, the null-terminator byte is 
not copied: it just does a `memcpy` with the length of the string, where the length does not include the 
terminator. 
 * The JSRT implementation does not handle numbers like the V8 implementation does. 
 * If it's possible to get a string from a number value, why not other primitive types (symbol, boolean, 
null/undefined)? We should check the V8 behavior for all of those and try to be consistent. 
 * The JSRT implementation does not copy the null terminator. It assumes `JsCopyStringUtf8` does copy 
the terminator (it does not), and that incorrect assumption also leads to an incorrect 
remaining return value. 

That last item in the list above causes the `test_string` and `test_object` test cases to fail in the NAPI 
chakracore branch.

**Comment by jasongin** [comment]
The `Utf8String` constructor in `node_api_helpers.h` also mistakenly assumes the return value from `napi_get_string_value` is the number of bytes written, not remaining.

**Comment by bnoordhuis** [comment]
> If it's possible to get a string from a number value, why not other primitive types (symbol, boolean, null/undefined)? We should check the V8 behavior for all of those

It's quite complex.  `v8::Utf8Value::Utf8Value(...`):

1. Performs the equivalent of .toString() on primitives (strings, numbers, etc, but not symbols.)
2. Tries `[Symbol.toPrimitive]`, .toString() and .valueOf() in that order on objects.
3. If those methods don't exist, don't complete successfully, or don't produce a string, it raises an exception.
4. Trying to stringify a symbol raises an exception.

I say "equivalent of .toString()" because it doesn't actually invoke the method.  Monkey-patching e.g. `Number.prototype.toString` has no effect.
