### ISSUE TITLE
Remove napi_get_current_env()

### ISSUE THREAD

**Issue by jasongin** [nodejs/abi-stable-node#96]
According to a [comment](https://github.com/nodejs/abi-stable-node/pull/58/commits/40e02b71b1ab22d04f7a8c347714ca75ac898736#r100386021) from @kkoopa, `Isolate::GetCurrent()` might go away. Therefore we should consider removing the corresponding API in NAPI, so that people don't write code that relies on it. It should not strictly be needed anyway.

**Comment by mhdawson** [comment]
Seems to have been added in https://github.com/nodejs/abi-stable-node/commit/db152ec1f4dca6fc65c718b4b37dfcffe8623609.

I would agree that we want to avoid it if we are not actually using it and force people to pass through the env that they get when the initial c function is called.

**Comment by jasongin** [comment]
Currently `napi_get_current_env()` is used by the code in `node_api_helpers.h`. But the new C++ wrappers make almost all that code obsolete anyway. (I haven't yet built an updated version of `Napi::AsyncWorker`.)

**Comment by kkoopa** [comment]
I'll go slightly off-topic again: Regarding `AsyncWorker` I would advise a couple changes compared to the NAN implementation: A factory to create `AsyncWorker`s so the user does not have to do `new AsyncWorker(new Callback())`, as all that is more Java than idiomatic C++, `new` in user code is considered bad nowadays. Maybe ignore `Nan::Callback` altogether, since calling the wrapped function may or may not need to be done using `node::MakeCallback` or a straight function call, depending on whether the invocation happens from a libuv callback or from within V8.

Another unrelated thing: Reevaluate whether classes from NAN should be movable or not, i.e. `NAN_DISALLOW_ASSIGN_COPY_MOVE`, the disallowed moving was part conservatism, part legacy from before C++11. We figured it was easier to retroactively allow moving than putting the genie back in the bottle.

**Comment by mhdawson** [comment]
I'm not quite sure we are ready to make all of the helper functionality like "AsyncWorkers" dependent on the full C++ wrapper until we figure out the performance results from Canvas since they are much worse than we've seen from using the C api.    

I assume though, we could remove the dependency on napi_get_current_env() without doing that.

**Comment by jasongin** [comment]
I'm confident most of the canvas performance issues are not due to use of the C++ wrapper. Compared to other packages we have benchmarked some of the canvas tests are very fine-grained: the extreme ones do >10 million calls per second across the JS/C++ boundary.

**Comment by ianwjhalliday** [comment]
Ideally the C++ layer should be a zero-cost abstraction.  I would be surprised if it adds noticeable overhead.

napi_get_current_env() should indeed be removed.  @ofrobots had mentioned this a while back, I think in one of our early meetings, that Isolate::GetCurrent was planned to be deprecated and removed eventually.  No point in having NAPI start with a dependence on it.

**Comment by jasongin** [comment]
> Ideally the C++ layer should be a zero-cost abstraction.

While most of the wrapper will evaporate during compilation, it can't be completely zero-cost in some places because there is an extra level of function calls & indirection for the callbacks where the C callback is adapted to the C++ callback style.

Also, note that you aren't forced to use the C++ wrapper everywhere if you use it at all. For example it should be easy to only an AsyncWorker class, if that's all you want. All the C++ types are easily (often implicitly) convertible to/from the corresponding NAPI primitives.

**Comment by sampsongao** [comment]
Closed in e057a6f974203ad667b460521ced4b818cec4814
